octopus:
  replicated: true
  fully_replicated: true
  
  environments:
      - development
  
  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: octopus_bug_development_slave1
      pool: 5
      username: root
      password: 
      host: localhost
